# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       maui-release

# >> macros
%define release_name Maui
# << macros

Summary:    %{release_name} release files
Version:    2014.1
Release:    1
Group:      System/Base
License:    GPLv2
BuildArch:  noarch
URL:        http://www.maui-project.org/
Source100:  maui-release.yaml
Provides:   system-release = %{version}-%{release}
Provides:   moblin-release = 2.2
Provides:   meego-release  = 1.3
Provides:   mer-release
Obsoletes:   moblin-release <= 2.1.92-4.6
Obsoletes:   meego-release <= 1.2.90
Obsoletes:   mer-release

%description
%{release_name} release files such as various /etc/ files that define the release.

%prep
# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
install -d $RPM_BUILD_ROOT%{_sysconfdir}
echo "%{release_name} release %{version} (%{release_name})" > $RPM_BUILD_ROOT%{_sysconfdir}/mer-release
cp -p $RPM_BUILD_ROOT%{_sysconfdir}/mer-release $RPM_BUILD_ROOT%{_sysconfdir}/issue

echo "Kernel \r on an \m" >> $RPM_BUILD_ROOT%{_sysconfdir}/issue
cp -p $RPM_BUILD_ROOT%{_sysconfdir}/issue $RPM_BUILD_ROOT%{_sysconfdir}/issue.net
echo >> $RPM_BUILD_ROOT%{_sysconfdir}/issue

ln -s mer-release $RPM_BUILD_ROOT%{_sysconfdir}/system-release
ln -s mer-release $RPM_BUILD_ROOT%{_sysconfdir}/moblin-release
ln -s mer-release $RPM_BUILD_ROOT%{_sysconfdir}/meego-release


cat > $RPM_BUILD_ROOT%{_sysconfdir}/os-release <<EOF
NAME="%{release_name}"
VERSION="%{version}"
ID="maui"
ID_LIKE="mer"
VERSION_ID="%{version}"
PRETTY_NAME="%{release_name} %{version}"
ANSI_COLOR="0;34"
HOME_URL="http://www.maui-project.org/"
EOF

# Add the gpg-key here when available.
#mkdir -p $RPM_BUILD_ROOT%{_sysconfdir}/pki/rpm-gpg
#cp %{SOURCE0} $RPM_BUILD_ROOT%{_sysconfdir}/pki/rpm-gpg
#ln -sf RPM-GPG-KEY-maui $RPM_BUILD_ROOT%{_sysconfdir}/pki/rpm-gpg/RPM-GPG-KEY-maui-2-primary
# << install post

%files
%defattr(-,root,root,-)
%config %attr(0644,root,root) %{_sysconfdir}/mer-release
%config %attr(0644,root,root) %{_sysconfdir}/os-release
%{_sysconfdir}/system-release
%{_sysconfdir}/moblin-release
%{_sysconfdir}/meego-release
%config(noreplace) %attr(0644,root,root) %{_sysconfdir}/issue
%config(noreplace) %attr(0644,root,root) %{_sysconfdir}/issue.net
# >> files
# << files
